export enum AmenityCategory {
  BASIC = 'BASIC',
  FACILITIES = 'FACILITIES',
  FAMILY_FEATURES = 'FAMILY_FEATURES',
  DINING = 'DINING',
  LOGISTICS = 'LOGISTICS',
  BED_AND_BATH = 'BED_AND_BATH',
  OUTDOOR = 'OUTDOOR',
  SAFETY = 'SAFETY'
}